require('../fonts/suisse-bp-regular.woff2')
require('../fonts/suisse-bp-regular.woff')
require('../fonts/suisse-bp-light.woff2')
require('../fonts/suisse-bp-light.woff')
require('../fonts/suisse-bp-ultra-light.woff')
require('../fonts/suisse-bp-ultra-light.woff')
require('../fonts/george-x-regular.woff2')
require('../fonts/george-x-regular.woff')
